use std::{fs, process::Command};

use ra::config::RaConfig;
use tempfile::TempDir;

fn ra_bin() -> &'static str {
    env!("CARGO_BIN_EXE_ra")
}

fn run_ra_init(dir: &std::path::Path, args: &[&str]) -> std::process::Output {
    Command::new(ra_bin())
        .arg("init")
        .args(args)
        .current_dir(dir)
        .output()
        .expect("run ra init")
}

#[test]
fn init_scaffolds_parseable_project_config_and_skills_dir() {
    let tmp = TempDir::new().unwrap();

    let output = run_ra_init(tmp.path(), &[]);
    assert!(
        output.status.success(),
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let config_path = tmp.path().join("ra.toml");
    let skills_dir = tmp.path().join(".ra").join("skills");
    assert!(config_path.exists(), "ra.toml should be created");
    assert!(skills_dir.is_dir(), ".ra/skills should be created");

    let raw = fs::read_to_string(config_path).unwrap();
    let cfg: RaConfig = toml::from_str(&raw).expect("generated ra.toml should parse");
    assert_eq!(cfg.version, 1);
    assert!(cfg.skills.enabled);
    assert!(cfg.skills.discover);
}

#[test]
fn init_is_idempotent_unless_force_is_set() {
    let tmp = TempDir::new().unwrap();
    let config_path = tmp.path().join("ra.toml");

    assert!(run_ra_init(tmp.path(), &[]).status.success());
    fs::write(&config_path, "version = 1\n# user-owned config\n").unwrap();

    let second = run_ra_init(tmp.path(), &[]);
    assert!(second.status.success());
    assert_eq!(
        fs::read_to_string(&config_path).unwrap(),
        "version = 1\n# user-owned config\n",
        "second init must not overwrite existing config"
    );

    let forced = run_ra_init(tmp.path(), &["--force"]);
    assert!(forced.status.success());
    let forced_config = fs::read_to_string(&config_path).unwrap();
    assert!(
        forced_config.contains("Generated by `ra init`"),
        "--force should replace the generated file"
    );
    assert!(!forced_config.contains("user-owned config"));
}

#[test]
fn init_can_add_example_skill_without_overwriting_it_on_rerun() {
    let tmp = TempDir::new().unwrap();
    let skill_path = tmp
        .path()
        .join(".ra")
        .join("skills")
        .join("example")
        .join("SKILL.md");

    assert!(run_ra_init(tmp.path(), &["--example-skill"])
        .status
        .success());
    assert!(skill_path.exists(), "example skill should be created");

    fs::write(&skill_path, "---\nname: custom\n---\n").unwrap();
    assert!(run_ra_init(tmp.path(), &["--example-skill"])
        .status
        .success());
    assert_eq!(
        fs::read_to_string(&skill_path).unwrap(),
        "---\nname: custom\n---\n",
        "example skill should not be overwritten without --force"
    );
}
