//! Project scaffolding for `ra init`.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

const RA_TOML_TEMPLATE: &str = r#"# Ra project config. Generated by `ra init`.
# Resolution order: `--config` -> `$RA_CONFIG` -> `./ra.toml` -> `~/.ra.toml`.

version = 1

[run]
banner = true
# data_dir = "~/.local/share/ra"   # ATIF/ATOF session data root
# default_cwd = "."

# Pick a default model by uncommenting one `[[models]]` entry and setting
# the matching API key in your environment. With no model configured and no
# API key present, Ra falls back to its mock model.
[model]
# default = "anthropic"

# [[models]]
# name = "anthropic"
# backend = "anthropic"
# model_id = "claude-opus-4-5"
# api_key_env = "ANTHROPIC_API_KEY"

# [[models]]
# name = "openai"
# backend = "openai"
# model_id = "gpt-4.1-mini"
# api_key_env = "OPENAI_API_KEY"

[tools]
# Empty means: enable every built-in tool.
# Basic tools: read, write, edit, bash.
# Structured search tools: ast_grep.
# Native CLI tools: git, gh, jq.
# Extended tools: grep, glob, ls, fuzzy, apply_patch.
# Web docs tools: webfetch_fetch, webfetch_crawl.
# OpenSpec tool: openspec.
# Tmux tools: tmux_run, tmux_send, tmux_capture, tmux_kill, tmux_listen.
# builtin = ["read", "write", "edit", "bash", "ast_grep", "git", "gh", "jq", "grep", "glob", "ls", "fuzzy", "apply_patch", "webfetch_fetch", "webfetch_crawl", "openspec", "tmux_run", "tmux_send", "tmux_capture", "tmux_kill", "tmux_listen"]
builtin = []

[skills]
# `discover = true` loads project skills from `./.ra/skills/**/SKILL.md`
# shared cross-agent skills from `./.agents/skills/**/SKILL.md`, and
# Claude Code skills from `./.claude/skills/**/SKILL.md`.
enabled = true
discover = true
paths = []

[prompts]
enabled = true
paths = []

[agents_md]
enabled = true

# Native OpenSpec (https://github.com/Fission-AI/OpenSpec) discovery.
# Ra finds the nearest `openspec/` directory and folds its capability
# specs + active changes into the system prompt (progressive disclosure).
# `agent_own` (default true) also folds in the non-interactive,
# no-human-in-the-loop playbook for driving the `openspec` CLI.
[openspec]
enabled = true
# path = "./docs/openspec"   # override the auto-discovered location
# agent_own = true           # set false to surface the catalog only
"#;

const EXAMPLE_SKILL_TEMPLATE: &str = r#"---
name: example
description: Example project-local Ra skill.
---

# Example Skill

Use this skill when the user asks for project-specific Ra guidance.

## Instructions

- Prefer the conventions already present in this project.
- Keep responses concise and actionable.
"#;

#[derive(Debug, Clone, Copy, Default)]
pub struct InitOptions {
    pub force: bool,
    pub example_skill: bool,
}

#[derive(Debug, Default, Clone)]
pub struct InitReport {
    pub created: Vec<PathBuf>,
    pub overwritten: Vec<PathBuf>,
    pub skipped: Vec<PathBuf>,
}

/// Create the default Ra project layout under `root`.
///
/// Existing files are left untouched unless `options.force` is set.
pub fn init_project(root: &Path, options: InitOptions) -> Result<InitReport> {
    let mut report = InitReport::default();
    let skills_dir = root.join(".ra").join("skills");

    create_dir_if_missing(&skills_dir, &mut report)?;
    write_template(
        &root.join("ra.toml"),
        RA_TOML_TEMPLATE,
        options.force,
        &mut report,
    )?;

    if options.example_skill {
        write_template(
            &skills_dir.join("example").join("SKILL.md"),
            EXAMPLE_SKILL_TEMPLATE,
            options.force,
            &mut report,
        )?;
    }

    Ok(report)
}

fn create_dir_if_missing(path: &Path, report: &mut InitReport) -> Result<()> {
    if path.exists() {
        if !path.is_dir() {
            anyhow::bail!("{} exists but is not a directory", path.display());
        }
        return Ok(());
    }
    std::fs::create_dir_all(path).with_context(|| format!("create {}", path.display()))?;
    report.created.push(path.to_path_buf());
    Ok(())
}

fn write_template(path: &Path, contents: &str, force: bool, report: &mut InitReport) -> Result<()> {
    if path.exists() {
        if !path.is_file() {
            anyhow::bail!("{} exists but is not a regular file", path.display());
        }
        if !force {
            report.skipped.push(path.to_path_buf());
            return Ok(());
        }
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }

    let existed = path.exists();
    std::fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;

    if existed {
        report.overwritten.push(path.to_path_buf());
    } else {
        report.created.push(path.to_path_buf());
    }
    Ok(())
}
